2. Create complaints.csv in Jupyter

In [6]:
import pandas as pd

complaints = pd.DataFrame([
    {"complaint_id":"CMP-001","customer_id":1002,"category":"Billing",
     "description":"Charged extra for data usage","created_at":"2025/09/25 10:45",
     "status":"Open"},
    {"complaint_id":"CMP-002","customer_id":1004,"category":"Network",
     "description":"Frequent call drops in Delhi","created_at":"2025-09-25 09:30",
     "status":"Open"},
    {"complaint_id":"CMP-003","customer_id":1005,"category":"Recharge",
     "description":"Recharge failed; amount deducted","created_at":"25-09-2025 14:00",
     "status":"Closed"},
    {"complaint_id":"CMP-004","customer_id":1002,"category":"Network",
     "description":"Slow 4G speed at night","created_at":"2025-09-26 20:40",
     "status":"Open"},
    {"complaint_id":"CMP-005","customer_id":1003,"category":"Support",
     "description":"No response to complaint","created_at":"2025-09-26 11:10",
     "status":"Open"}
])

complaints.to_csv("complaints.csv", index=False)

# simple one‑liner:
print("✅ complaints.csv saved.")

# …or, if you prefer the extra lines:
# print("""✅
# complaints.csv saved.""")

✅ complaints.csv saved.

3) Build the ETL Pipeline

In [ ]:
from sqlalchemy import create_engine, text
# Mydb is engine
engine = create_engine("mysql+pymysql://root:Ritik%402004@localhost/bsnl_training")

connection = engine.connect()

print("Connected to database successfully")

with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))
    for row in result:
        print(row)

connection.close()

Connected to database successfully
('customers',)
('usage_data',)

4) EXTRACTING THE DATA

In [ ]:
# extrating data from  customer data 
customers = pd.read_sql("SELECT * FROM customers", engine) 

# Extract complaints from CSV 
complaints = pd.read_csv("complaints.csv")

print("Rows extracted -> Customers:", len(customers), "Complaints:", len(complaints))

print("Customer Data")
display(customers.head())
print("Complaints")
display(complaints.head())

Rows extracted -> Customers: 5 Complaints: 5
Customer Data

   customer_id         name plan_type   join_date   region
0         1001   Asha Mehta   Prepaid  2023-05-12    Delhi
1         1002   Ravi Kumar  Postpaid  2022-12-20   Mumbai
2         1003    Sneha Rao   Prepaid  2023-01-18  Chennai
3         1004  Manoj Singh  Postpaid  2021-11-05    Delhi
4         1005   Divya Jain   Prepaid  2023-03-28  Kolkata

Complaints

,complaint_id,customer_id,category,description,created_at,status
0,CMP-001,1002,Billing,Charged extra for data usage,2025/09/25 10:45,Open
1,CMP-002,1004,Network,Frequent call drops in Delhi,2025-09-25 09:30,Open
2,CMP-003,1005,Recharge,Recharge failed; amount deducted,25-09-2025 14:00,Closed
3,CMP-004,1002,Network,Slow 4G speed at night,2025-09-26 20:40,Open
4,CMP-005,1003,Support,No response to complaint,2025-09-26 11:10,Open

3.3 TRANSFORM Data (Clean, Fix, and Merge)

In [14]:
# --- Standardize text --- 
customers['region']  = customers['region'].str.title().str.strip() 
complaints['status'] = complaints['status'].str.title().str.strip() 
complaints['category'] = complaints['category'].str.title().str.strip()

In [15]:
# --- Parse and standardize dates --- 
customers['join_date']  = pd.to_datetime(customers['join_date'],  errors='coerce') 
complaints['created_at'] = pd.to_datetime(complaints['created_at'], errors='coerce')

In [16]:
# Fill unparseable or missing dates 
default_dt = pd.Timestamp('2025-09-25 00:00') 
customers['join_date']  = customers['join_date'].fillna(default_dt) 
complaints['created_at'] = complaints['created_at'].fillna(default_dt)

In [17]:
# --- Fix missing IDs or text --- 
complaints['customer_id'] = complaints['customer_id'].fillna(-1).astype(int) 
complaints['description'] = complaints['description'].fillna("No description provided")

In [20]:
# --- Merge --- 
merged = customers.merge(complaints, on='customer_id', how='left') 
# --- Post-merge fixes --- 
merged['complaint_id'] = merged['complaint_id'].fillna("NO-COMPLAINT") 
merged['category']     = merged['category'].fillna("No Complaint")
merged['status']       = merged['status'].fillna("Resolved") 
merged['created_at']   = merged['created_at'].fillna(default_dt)

In [28]:
# Derived flag 
merged['is_open'] = (merged['status'] == 'Open') 
print("✅ Data transformed successfully!")
merged

✅ Data transformed successfully!

,customer_id,name,plan_type,join_date,region,complaint_id,category,description,created_at,status,is_open
0,1001,Asha Mehta,Prepaid,2023-05-12,Delhi,NO-COMPLAINT,No Complaint,NaN,2025-09-25 00:00:00,Resolved,False
1,1002,Ravi Kumar,Postpaid,2022-12-20,Mumbai,CMP-001,Billing,Charged extra for data usage,2025-09-25 10:45:00,Open,True
2,1002,Ravi Kumar,Postpaid,2022-12-20,Mumbai,CMP-004,Network,Slow 4G speed at night,2025-09-25 00:00:00,Open,True
3,1003,Sneha Rao,Prepaid,2023-01-18,Chennai,CMP-005,Support,No response to complaint,2025-09-25 00:00:00,Open,True
4,1004,Manoj Singh,Postpaid,2021-11-05,Delhi,CMP-002,Network,Frequent call drops in Delhi,2025-09-25 00:00:00,Open,True
5,1005,Divya Jain,Prepaid,2023-03-28,Kolkata,CMP-003,Recharge,Recharge failed; amount deducted,2025-09-25 00:00:00,Closed,False

3.4 LOAD (Save the Output)

In [24]:
merged.to_csv("etl_output.csv", index=False) 
print(f"✅ ETL pipeline complete! Created {len(merged)} records and saved etl_output.csv.")

✅ ETL pipeline complete! Created 6 records and saved etl_output.csv.

4) Validation & Quick Analytics

In [26]:
print("\nComplaints per customer:") 
print(merged.groupby(['customer_id','name']).complaint_id.count().reset_index(name='complaint_count')) 
print("\nOpen vs Closed:") 
print(merged['status'].value_counts()) 
print("\nComplaints by region & category:") 
print(merged.groupby(['region','category']).complaint_id.count().reset_index(name='count'))

Complaints per customer:
   customer_id         name  complaint_count
0         1001   Asha Mehta                1
1         1002   Ravi Kumar                2
2         1003    Sneha Rao                1
3         1004  Manoj Singh                1
4         1005   Divya Jain                1

Open vs Closed:
status
Open        4
Resolved    1
Closed      1
Name: count, dtype: int64

Complaints by region & category:
    region      category  count
0  Chennai       Support      1
1    Delhi       Network      1
2    Delhi  No Complaint      1
3  Kolkata      Recharge      1
4   Mumbai       Billing      1
5   Mumbai       Network      1